// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ConfirmController from "./confirm_controller.js"
application.register("confirm", ConfirmController)

import FormController from "./form_controller.js"
application.register("form", FormController)

import InputController from "./input_controller.js"
application.register("input", InputController)

import PlacesController from "./places_controller.js"
application.register("places", PlacesController)

import PwaController from "./pwa_controller.js"
application.register("pwa", PwaController)

import SelectController from "./select_controller.js"
application.register("select", SelectController)

import ServiceWorkerController from "./service_worker_controller.js"
application.register("service-worker", ServiceWorkerController)
