require:
  - rubocop-rails
  - rubocop-performance

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - node_modules/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - lib/tasks/**/*
    - test/**/*
    - spec/**/*
    - vendor/bundle/**/*
    - app/controllers/pdfs_controller.rb
    - app/mailers/application_mailer.rb

Documentation:
  Enabled: false

Rails:
  Enabled: false

Metrics/ClassLength:
  Max: 160

Layout/LineLength:
  Max: 160

Style/HashSyntax:
  EnforcedStyle: 'ruby19_no_mixed_keys'
