development:
  online_payment:
    enabled: true

  medical_certificate:
    enabled: true

  signed_form:
    enabled: true

  payment_proof:
    enabled: true

test:
  online_payment:
    enabled: false

  medical_certificate:
    enabled: false

  signed_form:
    enabled: false

  payment_proof:
    enabled: true

production:
  online_payment:
    enabled: false

  medical_certificate:
    enabled: false

  signed_form:
    enabled: false

  payment_proof:
    enabled: true
