receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          relabel_configs:
            # Only keep targets with role label as 'web' or 'worker'
            - source_labels: [__meta_docker_container_label_role]
              regex: (web|worker)
              action: keep
            # Only scrape port 9394
            - source_labels: [__address__]
              regex: (.*):9394
              action: keep
            # Add container label
            - source_labels: [__meta_docker_container_label_role, __meta_docker_container_id]
              separator: "_"
              target_label: container
          static_configs:
            - targets: ['web:9394']
              labels:
                container: web
            - targets: ['worker:9394']
              labels:
                container: worker

exporters:
  prometheus:
    endpoint: 0.0.0.0:9394

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheus]
