# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a44002e10cc0bbb238cdebdd02cd3cf99a8611926e7b540e71a19b7411b4edd4ebc738c64a71cdd96744bd530e28e4c59413df03482b78c83a8f5a4d348c18b9

test:
  secret_key_base: ecefde2d4eab8e7d6159c47c89af1bbf9844c2faa10de9a96af8f64759aa09e3217e2fc0b3688057c449fb5015bce265d998e4ed2b9afc02a2360e691469e2c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
